# Generated by Django 2.2 on 2020-06-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, help_text='Phone Number', max_length=11)),
                ('dob', models.CharField(blank=True, help_text='Date of Birth', max_length=20)),
                ('gender', models.CharField(blank=True, help_text='Gender', max_length=10)),
                ('country_code', models.CharField(blank=True, help_text='Country Code', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
